### ISSUE TITLE
[Bug]: nightly API fails to load due to loot-core import

### ISSUE THREAD

**Issue by matt-fidd** [actualbudget/actual#5895]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

I'm guessing it's caused by https://github.com/actualbudget/actual/pull/5747

```
Error: Cannot find module 'loot-core/shared/util'
Require stack:
- /data/home/matt/cron/actual/node_modules/@actual-app/api/dist/utils.js
- /data/home/matt/cron/actual/node_modules/@actual-app/api/dist/index.js
```

### How can we reproduce the issue?

Use api nightly version past the 5th of the month
