### PR TITLE
fix `/info` endpoint not finding sync-server version in Docker

### LINKED ISSUE #5088: [Bug]: Error: Cannot find module '@actual-app/sync-server/package.json'
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

After upgrading to 25.6.0 using the docker release, the sync server shows the following error logs when a client connects:
```
actualbudget  | Checking if there are any migrations to run for direction "up"...
actualbudget  | Migrations: DONE
actualbudget  | Running in production mode - Serving static React app
actualbudget  | Listening on :::5006...
actualbudget  | 2025-06-04T08:26:44.216Z info: GET 304 /account/validate
actualbudget  | Error: Cannot find module '@actual-app/sync-server/package.json'
actualbudget  | Require stack:
actualbudget  | - /app/src/app.js
actualbudget  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
actualbudget  |     at Function.resolve (node:internal/modules/helpers:188:19)
actualbudget  |     at file:///app/src/app.js:54:37
actualbudget  |     at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)
actualbudget  |     at next (/app/node_modules/router/lib/route.js:157:13)
actualbudget  |     at Route.dispatch (/app/node_modules/router/lib/route.js:117:3)
actualbudget  |     at handle (/app/node_modules/router/index.js:435:11)
actualbudget  |     at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)
actualbudget  |     at /app/node_modules/router/index.js:295:15
actualbudget  |     at processParams (/app/node_modules/router/index.js:582:12)
actualbudget  | 2025-06-04T08:26:44.222Z info: GET 304 /account/needs-bootstrap
actualbudget  | 2025-06-04T08:26:44.532Z info: GET 304 /account/validate
actualbudget  | 2025-06-04T08:26:44.535Z info: GET 304 /sync/list-user-files
actualbudget  | 2025-06-04T08:26:44.542Z info: GET 304 /sync/list-user-files
actualbudget  | 2025-06-04T08:26:44.738Z info: POST 200 /sync/sync
actualbudget  | 2025-06-04T08:27:05.960Z info: POST 200 /sync/sync
actualbudget  | 2025-06-04T08:27:28.101Z info: POST 200 /sync/sync
actualbudget  | 2025-06-04T08:27:38.456Z info: POST 200 /sync/sync

```

Also the web-client shows N/A for the sync server version.

Image

Sync itself seems to work, though, I tried with my mobile client and the web-browser version, data was synced.

### How can we reproduce the issue?

Update from 25.5.0 docker version to 25.6.0. Stopping/starting the docker compose stack does not change the error.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

### PR DESCRIPTION
**Pull request by matt-fidd**
Fixes #5088

### CODE REVIEW

**Comment by matt-fidd** [comment]
Superseeded by https://github.com/actualbudget/actual/pull/5093
